---
f5_bigip_workflow:
  workflow: true
  author: 'Sean Cavanaugh'
  category: network
  name: 'WORKFLOW - F5 BIG-IP'
  description: 'Workflow for F5 BIG-IP to setup a VIP (Virtual IP) load balancer between two RHEL webservers'
  organization: 'Default'
  workshop_type:
    - f5
  schema:
    - job_template: 'F5 - add nodes'
      success:
        - job_template: 'F5 - add pool'
          success:
            - job_template: 'F5 - add pool members'
              success:
                - job_template: 'F5 - add virtual server'
  job_templates:
    f5_add_nodes:
      name: 'F5 - add nodes'
      description: 'add webserver nodes into F5 BIG-IP'
      job_type: 'run'
      inventory: 'Workshop Inventory'
      playbook: 'exercises/ansible_f5/1.2-add-node/bigip-node.yml'
      credential: 'Workshop Credential'
      survey_enabled: false
      project:
        name: 'Ansible Workshops Project'
        description: 'official workshops from Ansible'
        organization: 'Default'
        scm_type: git
        scm_url: 'https://github.com/ansible/workshops'
      workshop_type:
        - f5
    f5_add_pool:
      name: 'F5 - add pool'
      description: 'add webserver nodes into F5 BIG-IP'
      job_type: 'run'
      inventory: 'Workshop Inventory'
      playbook: 'exercises/ansible_f5/1.3-add-pool/bigip-pool.yml'
      credential: 'Workshop Credential'
      survey_enabled: false
      project:
        name: 'Ansible Workshops Project'
        description: 'official workshops from Ansible'
        organization: 'Default'
        scm_type: git
        scm_url: 'https://github.com/ansible/workshops'
      workshop_type:
        - f5
    f5_add_pool_members:
      name: 'F5 - add pool members'
      description: 'add webserver nodes into pool'
      job_type: 'run'
      inventory: 'Workshop Inventory'
      playbook: 'exercises/ansible_f5/1.4-add-pool-members/bigip-pool-members.yml'
      credential: 'Workshop Credential'
      survey_enabled: false
      project:
        name: 'Ansible Workshops Project'
        description: 'official workshops from Ansible'
        organization: 'Default'
        scm_type: git
        scm_url: 'https://github.com/ansible/workshops'
      workshop_type:
        - f5
    f5_add_vip:
      name: 'F5 - add virtual server'
      description: 'create VIP and add pool to virtual server'
      job_type: 'run'
      inventory: 'Workshop Inventory'
      playbook: 'exercises/ansible_f5/1.5-add-virtual-server/bigip-virtual-server.yml'
      credential: 'Workshop Credential'
      survey_enabled: false
      project:
        name: 'Ansible Workshops Project'
        description: 'official workshops from Ansible'
        organization: 'Default'
        scm_type: git
        scm_url: 'https://github.com/ansible/workshops'
      workshop_type:
        - f5
