---
collections:
  - name: ansible.controller
  - name: infra.ah_configuration
  - name: infra.controller_configuration
  - name: redhat_cop.controller_configuration
  # linux
  - name: ansible.posix
  - name: community.general
    version: ">=8.0.0"
  - name: containers.podman
  - name: redhat.insights
  - name: redhat.rhel_system_roles
  # windows
  - name: ansible.windows
  - name: chocolatey.chocolatey
  - name: community.windows
  # cloud
  - name: amazon.aws
  # satellite
  - name: redhat.satellite
  # network
  - name: ansible.netcommon
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.nxos
  # openshift
  - name: kubernetes.core
  - name: redhat.openshift
  - name: redhat.openshift_virtualization
