---
collections:
  - name: ansible.controller
    version: 4.3.0
  - name: redhat_cop.controller_configuration
    version: 2.2.5
  #linux
  - name: redhat.insights
    version: 1.0.7
  - name: redhat.rhel_system_roles
    version: 1.20.0
  - name: community.general
    version: 6.3.0
  - name: containers.podman
  #windows
  - name: chocolatey.chocolatey
  - name: community.windows
    version: 1.12.0
  - name: ansible.windows
    version: 1.13.0
  #cloud
  - name: azure.azcollection
    version: 1.14.0
  - name: amazon.aws
    version: 5.2.0
  #satellite
  - name: redhat.satellite
    version: 3.8.0
  #network
  - name: cisco.ios
    version: 3.1.0
  - name: cisco.nxos
    version: 3.0.0
  - name: cisco.iosxr
    version: 3.0.0
