---
- name: Create and publish AWS cloud reports
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    reports_aws_report: "{{ aws_report | default('tags') }}"
    reports_aws_region: "{{ create_vm_aws_region | default(reports_aws_region | default('us-east-1')) }}"
  tasks:
    - name: Include reports role
      ansible.builtin.include_role:
        name: demo.cloud.reports
