---
- hosts: "{{ HOSTS }}"
  gather_facts: no

  tasks:
  - name: list systems to be destroyed
    debug:
      msg: "{{ inventory_hostname }}"

  - name: pause for review...
    pause:
      seconds: 30
      prompt: "Systems listed above will be DESTROYED in 30 seconds. Cancel the job to Abort."

  - name: destroy vm
    include_role:
      name: "demo.cloud.aws"
      tasks_from: destroy_vm
    when: "'cloud_aws' in group_names"