---
- name: Patch ec2 Instance
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: true
  become: true

  tasks:
    - name: Include patching role
      when: tags.blueprint is match('rhel.*')
      ansible.builtin.include_role:
        name: "demo.cloud.aws"
        tasks_from: patch_vm

    - name: Demo patch failure path
      when: aws_demo_fail | default(false)
      ansible.builtin.assert:
        that: aws_demo_fail
        fail_msg: "Forcing a failure to demonstrate the patching failure path"
