---
- name: Patch ec2 Instance
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Include snapshot role
      when: tags.blueprint is match('rhel.*')
      ansible.builtin.include_role:
        name: "demo.cloud.aws"
        tasks_from: patch_vm
