---
- name: Snapshot ec2 instance
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Include snapshot role
      ansible.builtin.include_role:
        name: "demo.cloud.aws"
        tasks_from: snapshot_vm
