---
- name: Snapshot ec2 instance
  hosts: "{{ _hosts | default('aws_rhel8:aws_rhel9') }}:{{ _hosts_windows | default('aws-dc:aws_win1') }}"
  gather_facts: false

  tasks:
    - name: Include snapshot role
      ansible.builtin.include_role:
        name: "demo.cloud.aws"
        tasks_from: snapshot_vm
