---
- name: Windows updates
  hosts: "{{ HOSTS | default('os_windows') }}"
  vars:
    report_server: win1
  
  tasks:
  - include_role:
      name: demo.patching.patch_windows

  - block:

    - include_role:
        name: "{{ item }}"
      loop:
        - demo.patching.report_server
        - demo.patching.report_windows
        - demo.patching.report_windows_patching

    - include_role:
        name: demo.patching.report_server
        tasks_from: windows_landing_page

    delegate_to: "{{ report_server }}"
    run_once: yes
