---
- name: Uninstall Firefox on Windows
  hosts: "{{ HOSTS | default('os_windows') }}"

  tasks:
    - name: Uninstall Firefox on Windows
      ansible.windows.win_package:
        product_id: Mozilla Firefox
        arguments: /S
        state: absent
      register: windows_firefox_uninstall

    - name: Restart Windows when windows_firefox_uninstall == changed
      ansible.windows.win_reboot:
        reboot_timeout: 3600
      when: windows_firefox_uninstall.changed
