---
namespace: demo
name: satellite
version: 1.0.0+08062601
readme: README.md
authors:
  - Ansible Product Demos (https://github.com/ansible/product-demos)
description: Roles supporting Red Hat Satellite automation demos in ansible-product-demos.
license:
  - GPL-3.0-or-later
tags:
  - apd
  - satellite
  - linux
repository: https://github.com/ansible/product-demos
issues: https://github.com/ansible/product-demos/issues
...
