---
schemaVersion: 2.2.0
metadata:
  name: product-demos
components:
  - name: tooling-container
    container:
      image: quay.io/acme_corp/product-demos-ee:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
commands:
  - id: oc-install
    exec:
      commandLine: '/usr/local/bin/ansible-playbook ${PROJECT_SOURCE}/.install_oc.yaml'
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
        isDefault: true
      component: tooling-container
events:
  postStart:
    - "oc-install"
