---
namespace: ansible
name: product_demos
version: 1.2.1
readme: README.md

authors:
  - Sean Cavanaugh <seanc@redhat.com> @IPvSean

description: repository of demos to showcase Ansible features.

license:
  - GPL-3.0-or-later

tags:
  - apache
  - centos
  - rhel
  - el
  - amazon
  - linux
  - fedora
  - network
  - f5
  - developer
  - infrastructure
  - security
  - windows
  - opencap
  - insights
  - patching
  - tower
  - awx

dependencies: {}

repository: http://github.com/ansible/product-demos
documentation: http://github.com/ansible/product-demos
homepage: http://github.com/ansible/product-demos
issues: https://github.com/ansible/product-demos/issues
