---
- name: Configure multi-select setup job template.
  hosts: localhost
  vars:
    controller_components:
      - job_templates
    controller_templates:
      - name: Multi-SETUP demos
        project: Ansible official demo project
        playbook: multi_select_setup.yml
        inventory: Demo Inventory
        credentials:
          - Controller Credential
        survey_enabled: true
        survey:
          name: ''
          description: ''
          spec:
            - question_name: Which demos do you want to configure?
              type: multiselect
              variable: demos
              required: true
              default: "cloud\nlinux\nnetwork\nopenshift\nwindows"
              choices:
                - cloud
                - linux
                - network
                - openshift
                - satellite
                - windows
  tasks:
    - name: Demo Components
      ansible.builtin.include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0


