---
- name: Setup multiple just more than one demo
  hosts: localhost
  gather_facts: false
  vars:
    launch_jobs:
      name: "SETUP"
      wait: true
  tasks:
    - name: Build controller launch jobs
      ansible.builtin.set_fact:
        controller_launch_jobs: "{{ (controller_launch_jobs | d([]))
        + [launch_jobs | combine( {'extra_vars': { 'demo':  item }})] }}"
      loop: "{{ demos }}"

    - name: Default Components
      ansible.builtin.include_role:
        name: "infra.controller_configuration.job_launch"
