---
aws_provision_vm:
  author: "David Rojas"
  readme: "https://github.com/ansible/product-demos/blob/master/docs/infrastructure/azure_provision_vm.md"
  category: infrastructure
  name: "INFRASTRUCTURE / AWS Provision VM"
  description: "Provision RHEL VM on AWS with Ansible Tower Survey and Environmental variables"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/aws_provision_vm.yml"
  credential: "aws_credential"
  survey_enabled: true
  survey_spec:
    name: AWS Provision VM
    description: Provisioning a RHEL VM with Tower?
    spec:
      - type: text
        question_name: Enter name of the key pair to use
        question_description: This can be an existing or new key pair
        variable: keypair
        required: true
        #default: 
        
      - type: multiplechoice
        question_name: What AWS region do you want to host your EC2 instance
        question_description: Select one from the drop-down
        variable: aws_region
        required: true
        default: us-east-1
        choices:
          - us-east-1
          - us-west-1

      - type: text
        question_name: Enter the name of the VPC
        question_description: This will be the VPC in which your new EC2 instance will live 
        variable: vpc_name
        required: true

      - type: multiplechoice
        question_name: What instance type would you like to select
        question_description: Select one from the drop-down
        variable: instance_type
        required: true
        default: t2.micro
        choices:
          - t2.micro
          - t2.small
          - t2.medium       

      - type: text
        question_name: Enter the name of the EC2 instance
        question_description: You can't use any special characters or whitesapces
        variable: instance_name
        required: true
        #default:
  #video: "https://www.youtube.com/watch?v=pU8ZgSBuEJw&list=PLdu06OJoEf2bp-PNtxPP_2n7Avkax8TED"
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/davidrojas25/product-demos"
  workshop_type:
    - windows
    - demo
