---
azure_mysql_server:
  author: "David Rojas"
  readme: "https://github.com/ansible/product-demos/blob/master/docs/infrastructure/azure_mysql_server.md"
  category: infrastructure
  name: "INFRASTRUCTURE / Azure create a MySQL Server"
  description: "Provision MySQL server on Azure with Ansible Tower Survey and Environmental variables"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/infrastructure/azure_mysql_server.yml"
  credential: "azure_credential"
  survey_enabled: true
  survey_spec:
    name: Azure mysql server
    description: Provisioning a mySQL server in Azure
    spec:
      - type: text
        question_name: Enter name of your resource group
        question_description: This can be an existing or new resource group
        variable: resource_group
        required: true
        #default: 
        
      - type: multiplechoice
        question_name: What Azure region do you want to host your VM
        question_description: Select one from the drop-down
        variable: location
        required: true
        default: eastus 
        choices:
          - eastus
          - eastus2   
          - westus
          - centralus

      - type: text
        question_name: Enter the name of MySQL Server Database
        question_description: You can't use any special characters or whitesapces
        variable: sqlserver_name
        required: true
        #default:

      - type: text
        question_name: Set the name of the Admin user
        question_description: This will be used to login to your mySql. Do not use Admin or other reserved names
        variable: admin_user
        required: true

      - type: password
        question_name: Set the admin password to use
        question_description: This will be used to login to your mySQL. Must be at least 8 characters long, must contain upper adn lower case, numbers, and special character.
        variable: admin_pw
        required: true    
  #video: "https://www.youtube.com/watch?v=pU8ZgSBuEJw&list=PLdu06OJoEf2bp-PNtxPP_2n7Avkax8TED"
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/davidrojas25/product-demos"
  workshop_type:
    - windows
    - demo
