---
- name: add aws credential
  tower_credential:
    name: aws_credential
    description: AWS Credential 
    organization: "{{ vars[demo].project.organization }}"
    state: present
    kind: aws
    username: "{{ my_access_key }}"
    password: "{{ my_secret_key }}"
    tower_username: "{{ my_tower_username }}"
    tower_password: "{{ my_tower_password }}"
    tower_host: "{{ my_tower_host }}"


  
      


