---
win_update_categories:  # noqa var-naming[no-role-prefix] - TODO : we should rework roles to use variable prefix, until scope is defined, silence is the way
  - Application
  - Connectors
  - CriticalUpdates
  - DefinitionUpdates
  - DeveloperKits
  - FeaturePacks Guidance
  - SecurityUpdates
  - ServicePacks
  - Tools
  - UpdateRollups
  - Updates
allow_reboot: true  # noqa var-naming[no-role-prefix] - TODO : we should rework roles to use variable prefix, until scope is defined, silence is the way
