---
- name: Add AH collection token to repo and sync repository
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add Console AH token
      infra.ah_configuration.collection_remote:
        name: "{{ item.name }}"
        url: "{{ item.url }}"
        auth_url: "{{ item.auth_url }}"
        token: "{{ ah_token }}"
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      loop: "{{ ah_collection_remotes }}"

    - name: Sync repositories in AH (this can take a while)
      infra.ah_configuration.collection_repository_sync:
        name: "{{ item.name }}"
        wait: true
        timeout: 1500
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      loop: "{{ ah_collection_remotes }}"
