---
- name: Configure AH credential for registry and sync EEs
  hosts: localhost
  vars:
    remove_ee_repositories:
      - name: ansible-automation-platform-24/ee-29-rhel8
      - name: ansible-automation-platform-24/ee-minimal-rhel8	
      - name: ansible-automation-platform-24/ee-minimal-rhel9
      - name: ansible-automation-platform-24/ee-supported-rhel8
      - name: ansible-automation-platform-24/ee-supported-rhel9
      - name: ansible-automation-platform/ee-29-rhel8
      - name: ansible-automation-platform/ee-minimal-rhel8
      - name: ansible-automation-platform/ee-minimal-rhel9
      - name: rhoso-edpm-beta/ee-openstack-ansible-ee-rhel9
      - name: rhoso-operators/ee-openstack-ansible-ee-rhel9

  gather_facts: false
  tasks:
    - name: Assert non-default credentials
      ansible.builtin.assert:
        that:
          - lookup('ansible.builtin.env', 'REGISTRY_USERNAME') != 'CHANGEME'
        fail_msg: "Please provide `Usable Automation Hub Credential`"

    # This should not be necessary, but for some reason, superfulious repositories have led to sync failures
    - name: Remove default EE repositories
      infra.ah_configuration.ah_ee_repository:
        name: "{{ item }}"
        state: absent
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      loop: "{{ remove_ee_repositories | map(attribute='name') | difference(ah_ee_repositories | map(attribute='name')) }}"

    - name: Add Console EE credential to EE Registry
      infra.ah_configuration.ah_ee_registry:
        name: "{{ item.name }}"
        url: "{{ item.url }}"
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        username: "{{ lookup('ansible.builtin.env', 'REGISTRY_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'REGISTRY_PASSWORD') }}"
      loop: "{{ ah_ee_registries }}"

    - name: Create EE repository
      infra.ah_configuration.ah_ee_repository:
        name: "{{ item.name }}"
        registry: "{{ item.registry }}"
        state: present
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      loop: "{{ ah_ee_repositories }}"


#    - name: Index AH registries
#      infra.ah_configuration.ah_ee_registry_index:
#        name: "{{ item.name }}"
#        wait: true
#        timeout: 300
#        ah_host: "{{ automation_hub_url }}"
#        ah_username: 'admin'
#        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
#      loop: "{{ ah_ee_registries }}"

    # Not sure if this is a limitation of our AH deployment, or a bug,
    # but the wait feature does not succeed, see the regries/until for 'Sync images'
    - name: Sync AH registries
      infra.ah_configuration.ah_ee_registry_sync:
        name: "{{ item.name }}"
        wait: false
        timeout: 1500
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      loop: "{{ ah_ee_registries }}"

    - name: Sync images
      infra.ah_configuration.ah_ee_image:
        name: "{{ item.name }}"
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      loop: "{{ ah_ee_repositories }}"
      retries: 80
      register: sync_image
      delay: 10
      until: sync_image is succeeded
