---
- name: Add AH token to repo and Sync AutomationHub
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add AH token
      infra.ah_configuration.collection_remote:
        name: rh-certified
        token: "{{ ah_token }}"
        url: https://console.redhat.com/api/automation-hub/content/published/
        auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"

    - name: Sync repositories in AH (this can take a while)
      infra.ah_configuration.collection_repository_sync:
        name: rh-certified
        wait: true
        timeout: 1500
        ah_host: "{{ automation_hub_url }}"
        ah_username: 'admin'
        ah_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
