---
- name: Deploy ACME App stylesheet
  ansible.builtin.copy:
    src: style.css
    dest: /var/www/html/style.css
    owner: root
    group: root
    mode: "0644"
    setype: httpd_sys_content_t

- name: Render ACME App index from Jinja template
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"
    setype: httpd_sys_content_t
