---
- name: Inlcude system variables
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Install httpd package
  ansible.builtin.yum:
    name: httpd
    state: installed
  check_mode: false

- name: Create reports directory
  ansible.builtin.file:
    path: "{{ doc_root }}/{{ reports_dir }}"
    state: directory
    mode: "0775"
  check_mode: false

- name: Copy .htaccess
  ansible.builtin.copy:
    dest: "{{ doc_root }}/{{ reports_dir }}/.htaccess"
    content: Options +Indexes
    mode: "0644"
  check_mode: false

- name: Install httpd service
  ansible.builtin.service:
    name: httpd
    state: started
  check_mode: false
