---
config_drift_kafka_image: docker.io/apache/kafka:3.9.0
config_drift_kafka_container_name: kafka
config_drift_kafka_port: 9092
config_drift_kafka_local_port: 9094
config_drift_kafka_external_port: 9095
config_drift_kafka_topic: linux-audit-events
config_drift_kafka_cluster_id: MkU3OEVBNTcwNTJENDM2Qk
config_drift_kafka_vpc_cidr: 10.0.0.0/16
config_drift_kafka_broker_heap_opts: "-Xmx1g -Xms1g"
config_drift_kafka_admin_heap_opts: "-Xmx256m -Xms128m"
