---
- name: Backup Containerlab Network Devices
  hosts: containerlab
  gather_facts: false

  vars:
    backup_dir: /tmp/network_backups

  tasks:
    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.run
      vars:  # noqa var-naming[no-role-prefix]
        operation: backup
        type: full
        data_store:
          local: "{{ backup_dir }}"

    - name: Remove non config lines
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "{{ backup_dir }}/{{ inventory_hostname }}.txt"
        line: "Building configuration..."
        state: absent
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Display backup location
      run_once: true
      ansible.builtin.debug:
        msg: "Backups saved to {{ backup_dir }}/ on the execution node"
