---
# defaults file for cluster_config
cluster_config_operators:
  - cnv
  - kafka

cluster_config_cnv:
  checkplan: true
  namespace:
    name: &cluster_config_cnv_namespace openshift-cnv
  operator_group:
    name: kubevirt-hyperconverged-group
    target_namespaces:
      - *cluster_config_cnv_namespace
  subscription:
    name: kubevirt-hyperconverged
  extra_resources:
    - apiVersion: hco.kubevirt.io/v1beta1
      kind: HyperConverged
      metadata:
        name: kubevirt-hyperconverged
        namespace: *cluster_config_cnv_namespace
      spec:
        BareMetalPlatform: true

cluster_config_kafka:
  checkplan: true
  namespace:
    name: &cluster_config_kafka_namespace openshift-kafka
  operator_group:
    name: global-operators
    target_namespaces:
      - *cluster_config_kafka_namespace
  subscription:
    name: amp-streams
  extra_resources:
    - apiVersion: kafka.strimzi.io/v1beta2
      kind: kafka
      metadata:
        name: my_cluster
        namespace: *cluster_config_kafka_namespace
      spec:
        BareMetalPlatform: true