---
# defaults file for cluster_config
cluster_config_operators:
  - cnv

cluster_config_cnv:
  checkplan: true
  namespace:
    name: &cluster_config_cnv_namespace openshift-cnv
  operator_group:
    name: kubevirt-hyperconverged-group
    target_namespaces:
      - *cluster_config_cnv_namespace
  subscription:
    name: kubevirt-hyperconverged
  extra_resources:
    - apiVersion: hco.kubevirt.io/v1beta1
      kind: HyperConverged
      metadata:
        name: kubevirt-hyperconverged
        namespace: *cluster_config_cnv_namespace
      spec:
        BareMetalPlatform: true

cluster_config_mce:
  checkplan: true
  namespace:
    name: &cluster_config_mce_namespace multicluster-engine
  operator_group:
    name: multicluster-engine
    target_namespaces:
      - *cluster_config_mce_namespace
  subscription:
    name: multicluster-engine
    channel: stable-2.11
  extra_resources:
    - apiVersion: multicluster.openshift.io/v1
      kind: MultiClusterEngine
      metadata:
        name: multiclusterengine
      spec:
        availabilityConfig: Basic
        overrides:
          components:
            - name: hypershift
              enabled: true
            - name: hypershift-local-hosting
              enabled: true
