---
collections:
  - name: ansible.controller
    version: ">=4.5.5"
  - name: infra.ah_configuration
    version: ">=2.0.6"
  - name: infra.controller_configuration
    version: ">=2.9.0"
  - name: redhat_cop.controller_configuration
    version: ">=2.3.1"
  # linux
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.general
    version: ">=8.0.0"
  - name: containers.podman
    version: ">=1.12.1"
  - name: redhat.insights
    version: ">=1.2.2"
  - name: redhat.rhel_system_roles
    version: ">=1.23.0"
  # windows
  - name: ansible.windows
    version: ">=2.3.0"
  - name: chocolatey.chocolatey
    version: ">=1.5.1"
  - name: community.windows
    version: ">=2.2.0"
  # cloud
  - name: amazon.aws
    version: ">=7.5.0"
  # satellite
  - name: redhat.satellite
    version: ">=4.0.0"
  # network
  - name: ansible.netcommon
    version: ">=6.0.0"
  - name: cisco.ios
    version: ">=7.0.0"
  - name: cisco.iosxr
    version: ">=8.0.0"
  - name: cisco.nxos
    version: ">=7.0.0"
  - name: infoblox.nios_modules
    version: ">=1.6.1"
  # openshift
  - name: kubernetes.core
    version: ">=4.0.0"
  - name: redhat.openshift
    version: ">=3.0.1"
  - name: redhat.openshift_virtualization
    version: ">=1.4.0"
