---
- name: Template HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ playbook_dir }}/index.html"
    mode: "0644"
  delegate_to: localhost
  run_once: true

- name: Copy CSS and pictures
  ansible.builtin.copy:
    src: "{{ role_path }}/files"
    dest: "{{ playbook_dir }}"
    directory_mode: '0755'
    mode: "0755"
    remote_src: true
  delegate_to: localhost
  run_once: true
