---
- name: Create web directory if it does not exist
  ansible.builtin.file:
    path: "{{ file_path }}"
    state: directory
    mode: "0755"

- name: Create HTML report
  check_mode: false
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/network.html"
    mode: "0644"

- name: Copy CSS over
  check_mode: false
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true
    mode: "0775"

- name: Copy logos over
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"
  loop_control:
    loop_var: logo
  check_mode: false
  ansible.builtin.copy:
    src: "{{ logo }}"
    dest: "{{ file_path }}"
    directory_mode: true
    mode: "0644"

- name: Display link to Linux patch report
  ansible.builtin.debug:
    msg: "Please go to http://{{ hostvars[report_server]['ansible_host'] }}/reports/network.html"
