- name: Create web directory if it does not exist
  ansible.builtin.file:
    path: "{{ file_path }}"
    state: directory
    mode: '0755'

- name: create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/network.html"
  check_mode: no

- name: copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true
  check_mode: no

- name: copy logos over
  ansible.builtin.copy:
    src: "{{ item }}" 
    dest: "{{ file_path }}"
    directory_mode: true
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"
  check_mode: no

# - name: Display link to Linux patch report
#   ansible.builtin.debug:
#     msg: "Please go to http://{{ hostvars[report_server]['ansible_host'] }}/reports/network.html"
