- name: Webhook demo prints all incoming events
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ port | default(5555) }}"
        host: 0.0.0.0
  rules:
    - name: Webhook rule
      condition: event.payload contains 'fapolicyd.service'
      action:
        print_event:
          pretty: true
    - name: debug
      condition: true
      debug:
        msg:
          - "first: {{ event[0] }}"
