- name: Webhook demo prints all incoming events
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ port | default(5555) }}"
        host: 0.0.0.0
  rules:
    - name: Webhook rule
      # condition: event.payload.message is select("==", "fapolicyd")
      condition: true
      action:
        debug:
          msg:
            - "{{ event }}" 
    - name: Condition rule
      condition:
        all:
          - event.message is defined
          - event.message is regex("fapolicyd")
      action:
        debug:
  
