- name: Webhook demo prints all incoming events
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ port | default(5555) }}"
        host: 0.0.0.0
  rules:
    - name: Webhook rule
      condition: event.payload.message contains 'fapolicyd.service'
      action:
        print_event:
          pretty: true
    - name: Debug
      condition: 1
      action:
        print_event:
          pretty: true