---
- name: Lookup VM names to be snapshotted
  hosts: "{{ _hosts }}"
  gather_facts: false
  tasks:
  - name: Get name of VirtualMachine
    ansible.builtin.set_stats: 
      data:
        my_var: "{{ ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    vars:
      ansible_connection: local

- name: Create a VM snapshot
  hosts: localhost
  tasks:
  - name: Get state of VirtualMachine
    redhat.openshift_virtualization.kubevirt_vm_info:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
    register: state

  - name: Stop VirtualMachine
    redhat.openshift_virtualization.kubevirt_vm:
      name: "{{ vm_namespace }}"
      namespace: "{{ vm_namespace }}"
      running: false
      wait: true
    when: state.resources.0.spec.running

  - name: Create a VirtualMachineSnapshot
    kubernetes.core.k8s:
      definition:
        apiVersion: snapshot.kubevirt.io/v1alpha1
        kind: VirtualMachineSnapshot
        metadata:
          generateName: "{{ vm_name }}-{{ ansible_date_time.iso8601 }}"
          namespace: "{{ vm_namespace }}"
        spec:
          source:
            apiGroup: kubevirt.io
            kind: VirtualMachine
            name: "{{ vm_name }}"
      wait: true
      wait_condition:
        type: Ready
    register: snapshot

  - name: Start VirtualMachine
    redhat.openshift_virtualization.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namesace }}"
      running: yes
      wait: yes
    when: state.resources.0.spec.running

  - name: Export snapshot name
    ansible.builtin.set_stats:
      data:
        restore_snapshot_name: "{{ snapshot.result.metadata.name }}"

  - debug:
      msg: "Successfully created snapshot {{ snapshot.result.metadata.name }}"

      ERROR! this task 'ansible.builtin.debug' has extra params, which is only allowed in the following modules: ansible.builtin.add_host, ansible.builtin.shell, ansible.legacy.group_by, ansible.legacy.command, ansible.builtin.include_vars, ansible.builtin.win_command, ansible.legacy.raw, include_role, ansible.builtin.include_tasks, include_vars, ansible.builtin.win_shell, ansible.builtin.import_tasks, ansible.legacy.include_role, ansible.builtin.include, ansible.builtin.include_role, ansible.windows.win_shell, script, ansible.legacy.win_shell, win_shell, ansible.builtin.import_role, shell, add_host, ansible.legacy.import_tasks, ansible.legacy.set_fact, set_fact, raw, import_role, ansible.legacy.include_vars, win_command, meta, ansible.builtin.group_by, ansible.legacy.script, ansible.legacy.include_tasks, ansible.builtin.meta, include_tasks, ansible.builtin.script, command, ansible.legacy.shell, ansible.legacy.add_host, ansible.legacy.import_role, group_by, include, ansible.windows.win_command, import_tasks…

