---
- name: Create a VM snapshot
  hosts: localhost
  tasks:
  - name: Get state of VirtualMachine
    redhat.openshift.kubevirt_vm_info:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
    register: state

  - name: Stop VirtualMachine
    redhat.openshift.kubevirt_vm:
      name: "{{ vm_namespace }}"
      namespace: "{{ vm_namespace }}"
      running: false
      wait: true
    when: state.resources.0.spec.running

  - name: Create a VirtualMachineSnapshot
    kubernetes.core.k8s:
      definition:
        apiVersion: snapshot.kubevirt.io/v1alpha1
        kind: VirtualMachineSnapshot
        metadata:
          generateName: "{{ vm_name }}-{{ ansible_date_time.iso8601 }}"
          namespace: "{{ vm_namespace }}"
        spec:
          source:
            apiGroup: kubevirt.io
            kind: VirtualMachine
            name: "{{ vm_name }}"
      wait: true
      wait_condition:
        type: Ready
    register: snapshot

  - name: Start VirtualMachine
    redhat.openshift.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namesace }}"
      running: yes
      wait: yes
    when: state.resources.0.spec.running

  - name: Export snapshot name
    ansible.builtin.set_stats:
      data:
        restore_snapshot_name: "{{ snapshot.result.metadata.name }}"

  - debug:
      msg: "Successfully created snapshot {{ snapshot.result.metadata.name }}"
