---
- name: Deploy OpenShift CNV Operator and create the Hyperconverged object
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include role
      ansible.builtin.incdlue_role:
        name: demo.openshift.cluster_config

