---
- name: Create a VM snapshot
  hosts: localhost
  vars:
    restore_snapshot_name: "{{ default(omit) }}"
  tasks:
  - name: Get state of VirtualMachine
    redhat.openshift_virtualization.kubevirt_vm_info:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
    register: state

  - name: Stop VirtualMachine
    redhat.openshift_virtualization.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
      running: no
      wait: yes
    when: state.resources.0.spec.running

  - name: Restore a VirtualMachineSnapshot
    kubernetes.core.k8s:
      definition:
        apiVersion: snapshot.kubevirt.io/v1alpha1
        kind: VirtualMachineRestore
        metadata:
          generateName: "{{ vm_name }}-"
          namespace: "{{ vm_namespace }}"
        spec:
          target:
            apiGroup: kubevirt.io
            kind: VirtualMachine
            name: "{{ vm_name }}"
          virtualMachineSnapshotName: "{{ restore_snapshot_name }}"
      wait: yes
      wait_condition:
        type: Ready

  - name: Start VirtualMachine
    redhat.openshift_virtualization.kubevirt_vm:
      name: "{{ vm_name }}"
      namespace: "{{ vm_namespace }}"
      running: yes
      wait: yes
    when: state.resources.0.spec.running
