---
- name: Slack Notification
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Make sure slack token is provided
      ansible.builtin.assert:
        that: 
          - slack_token is defined
          - aap_base_url is defined
          - slack_channel_name is defined
      run_once: true

    - name: Send notification message via Slack
      community.general.slack:
        token: "{{ slack_token }}"
        msg: >-
          A change request has been raised. 
          Please click on this URL to review the Digital Twin workflow: <{{ aap_base_url }}/#/jobs/workflow/{{ tower_workflow_job_id | default(omit) }}/output>

          Please click on this URL to release the code change: <{{ ansible_eda.event.payload.pull_request.html_url | default(omit) }}>
        channel: '#{{ slack_channel_name }}'
        username: 'Ansible_Digital_Twin'
        parse: 'none'
      run_once: true
