---
- name: Setup webserver and copy custom webpage
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:

  tasks:
  - name: Install httpd
    ansible.builtin.dnf:
      name: httpd
      state: present
    notify: Restart httpd

  - name: Create index.html
    ansible.builtin.copy:
      dest: "/var/www/html/index.html"
      src: templates/index.html
      mode: "0664"

  - name: Create image file
    ansible.builtin.copy:
      dest: "/var/www/html/"
      src: templates/benz_racing_redhat.jpg

  - name: Gather service facts
    ansible.builtin.service_facts:

  - name: Enable firewall http service
    ansible.posix.firewalld:
      service: http
      state: enabled
      immediate: true
      permanent: true
    when:
      - "'firewalld.service' in ansible_facts.services"
      - ansible_facts.services['firewalld.service']['state'] == 'running'

  - name: Disable httpd welcome page
    ansible.builtin.file:
      path: /etc/httpd/conf.d/welcome.conf
      state: absent
    notify: Restart httpd

  handlers:
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true