---
- name: Apply compliance profile
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:
    compliance_profile: undef

  tasks:
    - name: Check os type
      ansible.builtin.assert:
        that: "ansible_os_family == 'RedHat'"

    - name: Run Compliance Profile
      ansible.builtin.include_role:
        name: "demo.compliance.rhel{{ ansible_distribution_major_version }}STIG"
